### PR TITLE
Fix translation parameters

### PR DESCRIPTION
**Pull request by 3Dgoo**
Fixes issue #52

### CODE REVIEW

**Review by Turnerj — APPROVED** [review]

**Comment by Turnerj** [comment]
Actually I just double-checked Scrutinizer, apparently we still have that issue but it is on the last parameter... Will check this later when I have time.

**Comment by 3Dgoo** [comment]
I think this may be an issue with the API documentation. That last parameter on the function says it expects a string, but it should be an array.

**Comment by Turnerj** [comment]
Cool. I'll double check that and maybe create an issue on SilverStripe Framework for it before merging your changes in :)

**Comment by Turnerj** [comment]
Issue raised in framework: silverstripe/silverstripe-framework#7018

**Pull request merged**
